### ISSUE TITLE
Genome annotation with Infernal

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/docs#3]
Hi Eric!

This repo is the new Rfam documentation that I mentioned earlier. The docs are automatically deployed at http://rfam.readthedocs.io from the master branch, so Rfam team members can edit the text online using GitHub without having to access EBI servers.

I thought a page like this could be used to provide some examples of running Infernal locally:
http://rfam.readthedocs.io/en/latest/genome-annotation.html

Then we can point users to these examples when answering to RT tickets.

Would you be able to write a section (or a new page) about running Infernal and send a pull request please? Any feedback is of course very welcome too.

@nawrockie

**Comment by nawrockie** [comment]
Sure, Anton. Great idea.  I am happy to write a page about Infernal with some examples, but I'm busy this week. I should be able to get at least started on this next week.

**Comment by AntonPetrov** [comment]
Sounds good, thank you very much Eric!

**Comment by nawrockie** [comment]
Just an update -- I didn't have time this week (tomorrow is a holiday here) but have time set aside to start on this next week.

**Comment by AntonPetrov** [comment]
Thanks for the update! Enjoy your long weekend.

**Comment by nawrockie** [comment]
Anton, do you mind if I push my local branch to master as I'm making my edits, for backup reasons, and so I can potentially work on it from different computers?

**Comment by AntonPetrov** [comment]
Sure thing, Eric! You could also have your commits on a feature branch and
push it to GitHub and sync that way but if you prefer to push to master
it's fine too.

**Comment by nawrockie** [comment]
Push feature branch to master and make commits on the feature branch (and also push those commits to master) is what I meant. I won't commit directly to master until you've looked at it and approved.

**Comment by AntonPetrov** [comment]
Sounds great, thank you Eric! You meant master repo, not branch, I got it
now. Feel free to create as many feature branches as you need. Look forward
to merging your changes!

**Comment by AntonPetrov** [comment]
Closed with #16.
